version: '3.8'

services:
  csvserver:
    image: infracloudio/csvserver:latest
    container_name: csvserver
    ports:
      - "9393:9300"  # Map host port 9393 to container port 9300
    volumes:
      - ./inputFile:/csvserver/inputdata  # Mount inputFile into the container
    env_file:
      - csvserver.env  # Load environment variables from csvserver.env
